export const UPDATE_QUALIFIER = "UPDATE_QUALIFIER";
export const KNOCKOUT_DATA_FETCHED = "KNOCKOUT_DATA_FETCHED";
export const UPDATE_KNOCKOUT = "UPDATE_KNOCKOUT";

export const LOADING_DATA = "LOADING_DATA";
export const LOADING_ERROR = "LOADING_ERROR";
export const UPDATE_SCORE = "UPDATE_SCORE";
export const DATA_FETCHED = "DATA_FETCHED";