export const UPDATE_QUALIFIER = 'UPDATE_QUALIFIER';
export const KNOCKOUT_DATA_FETCHED = 'KNOCKOUT_DATA_FETCHED';
export const UPDATE_KNOCKOUT = 'UPDATE_KNOCKOUT';
export const REMOVE_TEAM = 'REMOVE_TEAM';

export const LOADING_DATA = 'LOADING_DATA';
export const LOADING_ERROR = 'LOADING_ERROR';
export const UPDATE_SCORE = 'UPDATE_SCORE';
export const DATA_FETCHED = 'DATA_FETCHED';

export const UPDATE_CHAMPIONS = 'UPDATE_CHAMPIONS';
export const REMOVE_CHAMPIONS = 'REMOVE_CHAMPIONS';
